import Unicode, {
  GlyphDirection,
  getGlyphDirections,
  UNICODE_CODE_VALUE,
  UNICODE_CHARACTER_NAME,
  UNICODE_GENERAL_CATEGORY,
  UNICODE_CANONICAL_COMBINING_CLASSES,
  UNICODE_BIDIRECTIONAL_CATEGORY,
  UNICODE_DECOMPOSITION_MAPPING,
  UNICODE_DECIMAL_DIGIT_VALUE,
  UNICODE_DIGIT_VALUE,
  UNICODE_NUMERIC_VALUE,
  UNICODE_MIRRORED,
  UNICODE_UNICODE_10_NAME,
  UNICODE_COMMENT_FIELD,
  UNICODE_UPPERCASE_MAPPING,
  UNICODE_LOWERCASE_MAPPING,
  UNICODE_TITLECASE_MAPPING,
} from "./Unicode";

let UNICODE_INSTANCE: Unicode = null;
export function defaultUnicode() {
  if (!UNICODE_INSTANCE) {
    UNICODE_INSTANCE = new Unicode();
    UNICODE_INSTANCE.loadLocally();
  }
  return UNICODE_INSTANCE;
}

export function setDefaultUnicode(unicode: Unicode) {
  UNICODE_INSTANCE = unicode;
}

export {
  GlyphDirection,
  getGlyphDirections,
  UNICODE_CODE_VALUE,
  UNICODE_CHARACTER_NAME,
  UNICODE_GENERAL_CATEGORY,
  UNICODE_CANONICAL_COMBINING_CLASSES,
  UNICODE_BIDIRECTIONAL_CATEGORY,
  UNICODE_DECOMPOSITION_MAPPING,
  UNICODE_DECIMAL_DIGIT_VALUE,
  UNICODE_DIGIT_VALUE,
  UNICODE_NUMERIC_VALUE,
  UNICODE_MIRRORED,
  UNICODE_UNICODE_10_NAME,
  UNICODE_COMMENT_FIELD,
  UNICODE_UPPERCASE_MAPPING,
  UNICODE_LOWERCASE_MAPPING,
  UNICODE_TITLECASE_MAPPING,
};
